<?php
declare(strict_types=1);

/* Pair data for the Life Path Compatibility Calculator.
   Keyed by the two single-digit root numbers, lowest first ("3-5").
   Master numbers (11, 22, 33) use their root digit (2, 4, 6) for the
   lookup. Server-side only: never included from a browser request. */

if (!defined('SPIRITUAL_APP')) {
    http_response_code(403);
    exit('Forbidden');
}

return [
    'scores' => [
        '1-1' => 65,
        '1-2' => 60,
        '1-3' => 85,
        '1-4' => 60,
        '1-5' => 90,
        '1-6' => 60,
        '1-7' => 80,
        '1-8' => 65,
        '1-9' => 70,
        '2-2' => 70,
        '2-3' => 65,
        '2-4' => 80,
        '2-5' => 55,
        '2-6' => 90,
        '2-7' => 55,
        '2-8' => 85,
        '2-9' => 80,
        '3-3' => 70,
        '3-4' => 50,
        '3-5' => 90,
        '3-6' => 80,
        '3-7' => 65,
        '3-8' => 50,
        '3-9' => 90,
        '4-4' => 70,
        '4-5' => 55,
        '4-6' => 85,
        '4-7' => 60,
        '4-8' => 90,
        '4-9' => 65,
        '5-5' => 70,
        '5-6' => 55,
        '5-7' => 85,
        '5-8' => 55,
        '5-9' => 75,
        '6-6' => 75,
        '6-7' => 60,
        '6-8' => 75,
        '6-9' => 90,
        '7-7' => 65,
        '7-8' => 60,
        '7-9' => 80,
        '8-8' => 70,
        '8-9' => 60,
        '9-9' => 70,
    ],
    'readings' => [
        '1-1' => ['title' => 'Two Leaders', 'sections' => [
            ['Overview', 'Two Life Path 1s share the same fire: independence, ambition, and a need to lead. The two of you recognize each other\'s drive instantly, which creates strong respect, and sometimes a quiet contest over who sets the direction.'],
            ['Strengths Together', 'Together you are bold, motivated, and unafraid to start big things. You understand each other\'s need for space, you inspire each other to aim higher, and neither of you needs to be convinced that goals are worth chasing. Mutual respect comes quickly.'],
            ['Challenges', 'Competition is the main risk. Two strong wills can clash over decisions, credit, or control, and neither wants to back down first. Pride may turn small disagreements into standoffs, and independence can slowly become distance.'],
            ['How to Make It Work', 'Divide leadership by area so each of you has your own territory, and celebrate each other\'s wins openly. Practice listening before responding. When you lead side by side instead of against each other, you become a formidable team.'],
        ]],
        '1-2' => ['title' => 'The Leader & the Peacemaker', 'sections' => [
            ['Overview', 'Life Path 1 and Life Path 2 meet as the leader and the peacemaker. One moves quickly and decisively, the other senses what everyone needs, creating a pairing that is very different yet naturally complementary.'],
            ['Strengths Together', 'The 1 brings courage, direction, and confidence, while the 2 brings empathy, patience, and diplomacy. You balance each other well: the 1 helps the 2 step forward, and the 2 helps the 1 slow down and listen.'],
            ['Challenges', 'The 1 may overlook the 2\'s feelings in pursuit of goals, while the 2 may swallow their needs to keep the peace. Over time, the 1 can feel held back, and the 2 can feel unseen or unimportant.'],
            ['How to Make It Work', 'The 1 should pause to ask and listen, and the 2 should speak up honestly and early. Appreciate what the other offers. When strength meets sensitivity with mutual respect, this match grows into a deeply supportive partnership. Small gestures of appreciation go a long way.'],
        ]],
        '1-3' => ['title' => 'The Leader & the Communicator', 'sections' => [
            ['Overview', 'Life Path 1 and Life Path 3 combine drive with joy. The 1 brings focus and ambition, and the 3 brings charm, humor, and imagination, so this match tends to feel lively, expressive, and full of forward momentum.'],
            ['Strengths Together', 'You motivate each other: the 1 encourages the 3 to pursue creative dreams, and the 3 helps the 1 relax and enjoy life. Shared optimism, confidence, and a love of fresh ideas make you an inspiring, energetic pair. Laughter and ambition travel comfortably together.'],
            ['Challenges', 'The 1 may become controlling or critical when the 3 seems scattered, while the 3 may feel boxed in by too much structure. The 3\'s sensitivity to criticism and the 1\'s bluntness can cause hurt feelings.'],
            ['How to Make It Work', 'Give the 3 room to create while the 1 provides gentle direction. Use humor to defuse tension, and speak kindly. When structure and spontaneity support each other, you become a vibrant, mutually encouraging duo. Keep it kind.'],
        ]],
        '1-4' => ['title' => 'The Leader & the Builder', 'sections' => [
            ['Overview', 'Life Path 1 and Life Path 4 pair vision with structure. The 1 starts things boldly, and the 4 builds them patiently, creating a practical, goal-oriented match grounded in shared seriousness about success. Neither of you minds hard work.'],
            ['Strengths Together', 'You make a productive team. The 1\'s initiative and the 4\'s discipline turn ideas into real results, and both of you respect effort, loyalty, and responsibility. Plans made together tend to be solid, realistic, and well executed.'],
            ['Challenges', 'The 1 may find the 4 slow or inflexible, while the 4 may see the 1 as impulsive and unwilling to follow a plan. Stubbornness on both sides can turn disagreements into long standoffs. Frustration builds when plans change.'],
            ['How to Make It Work', 'Let the 1 spark the direction and the 4 shape the process, and respect each other\'s pace. Compromise early, before frustration builds. When vision and reliability work together, this partnership becomes steady and truly productive. Patience on both sides pays off.'],
        ]],
        '1-5' => ['title' => 'The Leader & the Adventurer', 'sections' => [
            ['Overview', 'Life Path 1 and Life Path 5 are both independent and adventurous. The 1 charges ahead with purpose, and the 5 explores everything along the way, creating a pairing that feels exciting, dynamic, and rarely boring. Boredom is rarely a problem.'],
            ['Strengths Together', 'You share a love of freedom, new experiences, and bold action. Neither of you smothers the other, and your energy together feels fresh and spontaneous. Travel, projects, and big changes tend to bring you closer.'],
            ['Challenges', 'Both of you can be restless and strongly independent, which may leave little room for routine or commitment. The 1 may want control while the 5 wants flexibility, and you may drift apart if each simply goes their own way.'],
            ['How to Make It Work', 'Build shared goals and a few dependable routines to anchor your adventures. Communicate openly about expectations and keep your freedom balanced with loyalty. When you travel in the same direction, you make an exciting team. Keep promises, however small.'],
        ]],
        '1-6' => ['title' => 'The Leader & the Nurturer', 'sections' => [
            ['Overview', 'Life Path 1 and Life Path 6 bring together independence and devotion. The 1 pursues goals, and the 6 creates warmth and stability, so this match can feel like a strong leader supported by a caring heart.'],
            ['Strengths Together', 'The 6\'s nurturing nature gives the 1 a safe base, and the 1\'s confidence helps the 6 feel protected and inspired. Together you can build a loyal, secure partnership, where care and ambition both have a place. Loyalty is a strong thread between you.'],
            ['Challenges', 'The 6 may want more closeness and attention than the 1 naturally gives, while the 1 may feel smothered by responsibilities or advice. Controlling tendencies on either side can create resentment. Each of you may feel unappreciated at times.'],
            ['How to Make It Work', 'The 1 should show appreciation and make time for the relationship, while the 6 should trust the 1\'s independence. Clear boundaries and shared priorities keep love balanced. With mutual respect, this pairing becomes loyal and deeply supportive.'],
        ]],
        '1-7' => ['title' => 'The Leader & the Seeker', 'sections' => [
            ['Overview', 'Life Path 1 and Life Path 7 are two self-reliant minds. The 1 acts on instinct and ambition, while the 7 reflects deeply and searches for meaning, forming a pairing that is independent, intellectual, and often quiet. Mutual respect is your common ground.'],
            ['Strengths Together', 'You respect each other\'s space and individuality. The 1\'s drive gives the 7\'s ideas direction, and the 7\'s wisdom helps the 1 think before acting. Together you can build a relationship based on respect and shared curiosity.'],
            ['Challenges', 'Emotional distance is the main challenge. The 1 may seem too busy or forceful, and the 7 may withdraw or stay guarded. Neither may readily volunteer feelings, which can leave the relationship feeling cool or unspoken.'],
            ['How to Make It Work', 'Make deliberate time to talk about feelings, not just plans or ideas. The 1 can practice patience, and the 7 can practice openness. When you share your inner worlds, respect turns into real intimacy. Small shared rituals can bridge the quiet.'],
        ]],
        '1-8' => ['title' => 'The Leader & the Achiever', 'sections' => [
            ['Overview', 'Life Path 1 and Life Path 8 are two powerhouses. Both are ambitious, determined, and drawn to success, so this match tends to be goal-focused, strong-willed, and full of shared drive. Respect is immediate, and so is rivalry.'],
            ['Strengths Together', 'Together you can accomplish a great deal. The 1 brings originality and initiative, and the 8 adds strategy, organization, and staying power. You understand each other\'s ambition, and you respect competence and results. Few obstacles can stand in your way when you align.'],
            ['Challenges', 'Power struggles are the main risk. Both of you like control, and neither enjoys giving way. Work can crowd out romance, and pride may keep you from admitting mistakes or showing vulnerability. Stress can make both of you blunt.'],
            ['How to Make It Work', 'Share leadership by playing to each other\'s strengths, and make space for rest and affection. Treat each other as partners, not rivals. When ambition is shared, you become a formidable team with real staying power.'],
        ]],
        '1-9' => ['title' => 'The Leader & the Humanitarian', 'sections' => [
            ['Overview', 'Life Path 1 and Life Path 9 combine personal drive with universal compassion. The 1 pursues individual goals, and the 9 looks toward the bigger picture, creating a pairing that is idealistic, purposeful, and sometimes uneven. Each of you sees something admirable in the other.'],
            ['Strengths Together', 'The 9\'s generosity softens the 1\'s intensity, and the 1\'s confidence helps the 9 act on big ideals. You can inspire each other toward meaningful goals, and your values can complement each other beautifully.'],
            ['Challenges', 'The 1 may seem self-focused to the 9, while the 9 may seem too idealistic or detached to the 1. The 9\'s tendency to let go can clash with the 1\'s need to push ahead. Neither may notice when the other feels overlooked.'],
            ['How to Make It Work', 'Define a shared purpose that includes both personal achievement and contribution to others. Express appreciation often. When the 1\'s initiative and the 9\'s compassion work together, your partnership can feel both ambitious and meaningful.'],
        ]],
        '2-2' => ['title' => 'Two Peacemakers', 'sections' => [
            ['Overview', 'Two Life Path 2s create a gentle, intuitive partnership. Both of you are sensitive, cooperative, and attuned to feelings, so this match often feels deeply understanding, harmonious, and emotionally safe. Tenderness is your shared language.'],
            ['Strengths Together', 'You listen to each other, anticipate needs, and avoid harsh conflict. Cooperation comes naturally, and you create a calm, affectionate space together. Shared sensitivity helps you feel truly seen and understood. Small acts of care mean the world to both of you.'],
            ['Challenges', 'With neither partner naturally taking the lead, decisions can stall. You may both avoid difficult conversations, let resentments build quietly, or become overly sensitive to small slights. Dependence can slowly replace growth. Avoided topics tend to grow louder in silence.'],
            ['How to Make It Work', 'Practice making decisions together and speaking honestly, even when it feels uncomfortable. Encourage each other\'s independence and goals. When you balance gentleness with courage, your closeness becomes a stable, lasting strength. Courage to say the hard thing is your growth.'],
        ]],
        '2-3' => ['title' => 'The Peacemaker & the Communicator', 'sections' => [
            ['Overview', 'Life Path 2 and Life Path 3 pair sensitivity with sparkle. The 2 brings empathy and calm, and the 3 brings humor and expressiveness, creating a warm, affectionate match with plenty of emotional and creative connection.'],
            ['Strengths Together', 'The 3 lifts the 2\'s spirits and encourages them to open up, while the 2 listens, supports, and gives the 3 a safe audience. You appreciate each other\'s kindness and enjoy conversation, laughter, and shared affection. Affection flows easily when you feel safe together.'],
            ['Challenges', 'The 3\'s playfulness can sometimes feel careless to the 2, while the 2\'s sensitivity may feel heavy to the 3. Hurt feelings may go unspoken, and the 3\'s scattered energy can leave the 2 craving reassurance.'],
            ['How to Make It Work', 'Talk openly about feelings and show your appreciation often. The 3 can slow down to offer reassurance, and the 2 can share their needs lightly. With care and humor, you build a loving, expressive bond. Gentle honesty keeps things light.'],
        ]],
        '2-4' => ['title' => 'The Peacemaker & the Builder', 'sections' => [
            ['Overview', 'Life Path 2 and Life Path 4 are a steady, dependable pairing. The 2 offers emotional support and cooperation, and the 4 provides structure and reliability, so this match often feels secure, loyal, and grounded. Quiet loyalty defines your bond.'],
            ['Strengths Together', 'You value loyalty, patience, and commitment. The 4\'s stability gives the 2 a sense of safety, and the 2\'s warmth softens the 4\'s seriousness. Together you build practical, enduring foundations for home and family life. Each of you shows love through steady actions.'],
            ['Challenges', 'The relationship can become too routine or serious, and both of you may resist change. The 4 may seem emotionally reserved, while the 2 may crave more affection and reassurance than they receive.'],
            ['How to Make It Work', 'Make room for tenderness and fun inside your routines. The 4 can express appreciation more openly, and the 2 can voice their needs clearly. With care and consistency, this pairing grows into a secure, enduring bond. Celebrate small milestones together.'],
        ]],
        '2-5' => ['title' => 'The Peacemaker & the Adventurer', 'sections' => [
            ['Overview', 'Life Path 2 and Life Path 5 are very different in rhythm. The 2 seeks closeness and security, while the 5 seeks freedom and variety, making this pairing exciting yet sometimes challenging. Both of you may learn a lot from the contrast.'],
            ['Strengths Together', 'The 5 introduces the 2 to new experiences and helps them loosen up, while the 2 offers the 5 emotional depth and a loving anchor. When balanced, you broaden each other\'s lives in delightful ways.'],
            ['Challenges', 'The 2 may feel insecure when the 5 pulls away, and the 5 may feel restricted by the 2\'s need for closeness. Changes of plan, restlessness, and mixed signals can strain trust. Misreading each other\'s silence is common.'],
            ['How to Make It Work', 'Agree on how much togetherness and independence each of you needs. The 5 can offer consistent reassurance, and the 2 can trust the 5\'s loyalty. With patience, adventure and affection can live in the same relationship. Small rituals can steady the 2 while the 5 roams.'],
        ]],
        '2-6' => ['title' => 'The Peacemaker & the Nurturer', 'sections' => [
            ['Overview', 'Life Path 2 and Life Path 6 are among the most naturally harmonious numerology pairings. Both are caring, loyal, and relationship-focused, so this match tends to feel warm, affectionate, and deeply supportive. Home feels like home when you are together.'],
            ['Strengths Together', 'You share a love of home, family, and emotional closeness. The 2\'s sensitivity and the 6\'s responsibility create a nurturing partnership, where both of you give generously and appreciate each other\'s kindness. Kindness is returned generously on both sides.'],
            ['Challenges', 'Both of you may give so much that your own needs get neglected. The 6 can become controlling or worry too much, and the 2 can become overly dependent or avoid conflict. Unspoken resentment can quietly grow.'],
            ['How to Make It Work', 'Keep giving balanced, and be honest about your needs instead of sacrificing quietly. Make time for personal interests as well as shared ones. With healthy boundaries, this loving pairing becomes a lasting haven for both of you. Say what you need before it becomes a burden.'],
        ]],
        '2-7' => ['title' => 'The Peacemaker & the Seeker', 'sections' => [
            ['Overview', 'Life Path 2 and Life Path 7 combine sensitivity with depth. The 2 reaches toward emotional connection, and the 7 seeks understanding through solitude and thought, creating a gentle but sometimes mysterious match. Trust grows slowly but runs deep.'],
            ['Strengths Together', 'The 2\'s patience helps the 7 feel safe enough to open up, and the 7\'s wisdom gives the 2 insight and stability. You both appreciate quiet moments, meaningful conversation, and sincerity over superficiality. Silence can be shared without discomfort.'],
            ['Challenges', 'The 7\'s need for solitude can feel like rejection to the 2, while the 2\'s emotional needs may seem overwhelming to the 7. Unspoken feelings and silence can create misunderstanding. The 2 may take the 7\'s withdrawal personally.'],
            ['How to Make It Work', 'Explain your need for closeness and your need for space openly, so neither feels rejected. Create regular quiet time together. When patience meets honesty, this pairing becomes spiritually and emotionally deep. Reassurance without pressure helps the 7 return.'],
        ]],
        '2-8' => ['title' => 'The Peacemaker & the Achiever', 'sections' => [
            ['Overview', 'Life Path 2 and Life Path 8 pair gentleness with power. The 2 offers cooperation and emotional insight, and the 8 brings ambition and strength, forming a match that can be balanced when each respects the other. Success and sensitivity learn from each other here.'],
            ['Strengths Together', 'The 8\'s drive and security give the 2 confidence, while the 2\'s diplomacy helps the 8 handle people with grace. Together you can make an effective team, with emotional intelligence balancing strategic strength.'],
            ['Challenges', 'The 8 may focus too much on work and status, leaving the 2 feeling neglected. The 2 may feel overpowered or silenced, and the 8 may dismiss the 2\'s feelings as too sensitive. Respect can erode if feelings are brushed aside.'],
            ['How to Make It Work', 'The 8 should make time for tenderness and listen without judging, and the 2 should speak up with confidence. Respect each other\'s different strengths. When power and sensitivity work together, this match becomes quietly formidable.'],
        ]],
        '2-9' => ['title' => 'The Peacemaker & the Humanitarian', 'sections' => [
            ['Overview', 'Life Path 2 and Life Path 9 are both compassionate, sensitive souls. The 2 focuses on close partnership, and the 9 on the wider world, creating a caring match that is gentle, idealistic, and emotionally rich.'],
            ['Strengths Together', 'You share empathy, kindness, and a desire to help others. The 2\'s attentiveness grounds the 9\'s big-hearted ideals, and the 9\'s wisdom broadens the 2\'s perspective. Together you can build a relationship rooted in understanding and generosity. Gentleness runs through everything you do.'],
            ['Challenges', 'The 9\'s attention to causes and the wider world may leave the 2 feeling secondary. The 2\'s need for closeness may feel limiting to the 9. Both of you may avoid conflict instead of resolving it.'],
            ['How to Make It Work', 'Make your relationship a priority within your bigger goals, and speak honestly about needs. Share volunteer work or creative projects. When closeness and compassion go hand in hand, this pairing becomes tender and meaningful. Honest talks keep small hurts from growing.'],
        ]],
        '3-3' => ['title' => 'Two Communicators', 'sections' => [
            ['Overview', 'Two Life Path 3s make a lively, expressive, and entertaining pair. Both of you are creative, social, and optimistic, so this match often feels like a constant conversation filled with laughter and imagination. There is rarely a dull moment between you.'],
            ['Strengths Together', 'You understand each other\'s need for self-expression and fun. Ideas flow easily, humor keeps things light, and you encourage each other\'s creative projects. Together you bring joy to everyone around you. You make each other feel brilliant and appreciated.'],
            ['Challenges', 'Neither of you may be inclined to handle practical details, so bills, plans, and responsibilities can slip. Both of you may avoid serious conversations, chase distractions, or hurt each other with careless words. Moods may swing, and neither may steady the other.'],
            ['How to Make It Work', 'Create a simple system for responsibilities and set aside time for honest talks. Support each other\'s projects through to completion. When imagination and follow-through work together, your shared creativity can truly flourish.'],
        ]],
        '3-4' => ['title' => 'The Communicator & the Builder', 'sections' => [
            ['Overview', 'Life Path 3 and Life Path 4 combine creativity with structure. The 3 is spontaneous and expressive, and the 4 is disciplined and practical, making this a pairing of opposites that can either complement or frustrate. Each of you sees what the other lacks.'],
            ['Strengths Together', 'The 4 gives the 3\'s ideas a foundation, helping dreams become reality, and the 3 brings lightness and humor to the 4\'s seriousness. When respected, your differences make you stronger and more balanced together.'],
            ['Challenges', 'The 4 may see the 3 as unfocused or impractical, while the 3 may feel criticized or restricted by the 4\'s routines. Different attitudes toward money, time, and fun can create recurring friction. Money and time are likely flashpoints.'],
            ['How to Make It Work', 'The 4 can allow space for play and spontaneity, and the 3 can honor commitments and plans. Appreciate what each of you teaches the other. With flexibility and respect, you create a creative yet stable partnership. Humor helps bridge differences.'],
        ]],
        '3-5' => ['title' => 'The Communicator & the Adventurer', 'sections' => [
            ['Overview', 'Life Path 3 and Life Path 5 are one of the most playful, energetic pairings in numerology. Both are social, curious, and freedom-loving, so this match tends to feel exciting, flirtatious, and full of adventure. Spark and charm are never in short supply.'],
            ['Strengths Together', 'You enjoy conversation, travel, humor, and new experiences. Neither of you wants to be tied down, and you encourage each other to explore and express yourselves. Life together rarely feels boring or confining.'],
            ['Challenges', 'The same freedom that attracts you can undermine commitment. Both of you may avoid responsibility, overspend, or lose focus. Emotional depth may be overlooked in favor of fun, leaving serious matters unaddressed. Excess can sneak in.'],
            ['How to Make It Work', 'Create a shared foundation of trust and a few reliable routines. Talk about the future, not just the present. When you combine your free spirits with loyalty and planning, your partnership becomes both thrilling and lasting. Honesty about feelings keeps the fun real.'],
        ]],
        '3-6' => ['title' => 'The Communicator & the Nurturer', 'sections' => [
            ['Overview', 'Life Path 3 and Life Path 6 blend creativity with caring. The 3 brings fun and expression, and the 6 brings warmth and responsibility, forming a loving match with a natural sense of home and community. Warmth and playfulness make the relationship feel like home.'],
            ['Strengths Together', 'The 6\'s nurturing support helps the 3 feel valued and secure, while the 3\'s cheerfulness lightens the 6\'s burdens. You share a love of beauty, entertainment, and gathering people, and you make each other feel appreciated.'],
            ['Challenges', 'The 6 may become critical or controlling about the 3\'s casual habits, and the 3 may resist being managed. The 3\'s tendency to avoid obligations may leave the 6 carrying too much. Small frictions can pile up unnoticed.'],
            ['How to Make It Work', 'Share responsibilities fairly and let the 3 contribute in their own way. The 6 can relax expectations and enjoy the fun. With appreciation and flexibility, this pairing becomes a warm, creative, affectionate partnership. Gratitude goes a long way.'],
        ]],
        '3-7' => ['title' => 'The Communicator & the Seeker', 'sections' => [
            ['Overview', 'Life Path 3 and Life Path 7 are an intriguing mix of social sparkle and quiet depth. The 3 expresses everything outwardly, and the 7 explores inwardly, so this match depends on understanding different rhythms. Each of you is a puzzle the other enjoys.'],
            ['Strengths Together', 'The 3 brings lightness and communication to the 7\'s reserved world, and the 7 offers the 3 depth and perspective. When you appreciate each other, you can have fascinating conversations and learn a great deal.'],
            ['Challenges', 'The 3\'s love of socializing may overwhelm the 7, while the 7\'s need for solitude may feel like coldness to the 3. Misunderstandings arise when one wants company and the other wants quiet. Neither may know how to ask for what they need.'],
            ['How to Make It Work', 'Respect each other\'s different energy needs and schedule both social time and quiet time. Talk about feelings in your own styles. With patience, the 3 and 7 can learn from each other and grow in unexpected ways.'],
        ]],
        '3-8' => ['title' => 'The Communicator & the Achiever', 'sections' => [
            ['Overview', 'Life Path 3 and Life Path 8 pair creativity with ambition. The 3 communicates and inspires, and the 8 organizes and achieves, forming a match with strong potential when talents are shared and respected. Charm and drive create real momentum.'],
            ['Strengths Together', 'The 8\'s business sense and discipline give the 3\'s talents a platform, and the 3\'s charm and imagination add warmth and vision. Together you can build something both beautiful and profitable. Shared success can feel especially sweet.'],
            ['Challenges', 'The 8 may see the 3 as unfocused or careless with money, and the 3 may feel pressured by the 8\'s seriousness and control. The 8\'s work focus may leave the 3 feeling unappreciated.'],
            ['How to Make It Work', 'Agree on shared goals and respect each other\'s strengths. The 8 can encourage creativity without controlling it, and the 3 can show reliability. When ambition meets inspiration, this pairing can become both prosperous and joyful. Value each other\'s different kinds of intelligence.'],
        ]],
        '3-9' => ['title' => 'The Communicator & the Humanitarian', 'sections' => [
            ['Overview', 'Life Path 3 and Life Path 9 are both expressive, idealistic, and imaginative. The 3 brings joy and creativity, and the 9 brings compassion and wisdom, making this a warm, artistic, and generous match. Creative and compassionate energy flow freely.'],
            ['Strengths Together', 'You appreciate beauty, creativity, and meaningful causes. The 3\'s optimism lifts the 9\'s spirits, and the 9\'s depth gives the 3\'s ideas purpose. Together you can inspire people and share a joyful, generous life. Your shared warmth draws people toward you.'],
            ['Challenges', 'The 3\'s scattered focus can frustrate the 9, while the 9\'s emotional intensity or tendency to withdraw may confuse the 3. Both of you may avoid practical matters and expect the other to handle them.'],
            ['How to Make It Work', 'Use your creativity for projects that matter to both of you, and handle practical details together. Share feelings openly. When imagination and compassion meet, this pairing becomes inspiring and deeply fulfilling. Gentle accountability keeps dreams grounded.'],
        ]],
        '4-4' => ['title' => 'Two Builders', 'sections' => [
            ['Overview', 'Two Life Path 4s build a stable, loyal, and hard-working partnership. Both of you value responsibility and routine, so this match often feels secure, practical, and dependable. Trust is the cornerstone of your bond.'],
            ['Strengths Together', 'You understand each other\'s work ethic and respect commitments. Plans are made carefully, promises are kept, and you build a solid life together, with shared goals and a strong sense of loyalty. Your home and finances tend to be well managed.'],
            ['Challenges', 'With so much similarity in rigidity, change can be hard. Stubbornness may stall decisions, routines can become dull, and emotional expression may be limited. Work and duty can crowd out romance and play. Neither of you may notice when the relationship needs refreshing.'],
            ['How to Make It Work', 'Schedule fun, surprises, and affection as deliberately as you schedule everything else. Practice flexibility and talk about feelings. When you add warmth and spontaneity to your solid foundation, your bond becomes truly enduring. Small surprises can break the pattern.'],
        ]],
        '4-5' => ['title' => 'The Builder & the Adventurer', 'sections' => [
            ['Overview', 'Life Path 4 and Life Path 5 are opposites in rhythm. The 4 values order and stability, while the 5 craves change and freedom, so this match can be exciting, challenging, and full of learning. Respect for each other\'s differences is essential.'],
            ['Strengths Together', 'The 4 offers the 5 grounding and security, and the 5 helps the 4 loosen up and embrace new experiences. When you appreciate your differences, you balance each other and broaden each other\'s world.'],
            ['Challenges', 'The 4 may see the 5 as unreliable, and the 5 may feel restricted by the 4\'s routines and rules. Arguments about money, plans, and commitment can recur, and compromise can feel like losing. Patience is tested often.'],
            ['How to Make It Work', 'Agree on the essentials, such as finances and responsibilities, and leave room for spontaneity elsewhere. The 4 can try new things and the 5 can honor commitments. With flexibility, order and adventure can coexist. Neither style is wrong, only different.'],
        ]],
        '4-6' => ['title' => 'The Builder & the Nurturer', 'sections' => [
            ['Overview', 'Life Path 4 and Life Path 6 are a naturally harmonious, family-oriented pairing. Both are responsible, loyal, and committed, so this match tends to feel stable, caring, and deeply rooted. Your values line up naturally.'],
            ['Strengths Together', 'You share values around home, loyalty, and hard work. The 4 provides structure and security, and the 6 adds warmth and care. Together you create a dependable, nurturing environment and take commitments seriously. Family and tradition tend to matter to both of you.'],
            ['Challenges', 'Both of you can be rigid, and the 6 may become controlling or overly critical while the 4 may withhold emotion. Duty can take over and leave little room for spontaneity, play, or personal needs. Worry can quietly weigh on the relationship.'],
            ['How to Make It Work', 'Make time for rest, fun, and affection, not only duty. Voice appreciation openly and share responsibilities fairly. When practical reliability meets warmth, this pairing creates a lasting, loving foundation. Allow each other mistakes without criticism.'],
        ]],
        '4-7' => ['title' => 'The Builder & the Seeker', 'sections' => [
            ['Overview', 'Life Path 4 and Life Path 7 are a thoughtful, serious pairing. The 4 is practical and methodical, and the 7 is analytical and introspective, so this match often feels calm, respectful, and quietly intellectual. Mutual respect is the foundation here.'],
            ['Strengths Together', 'You both value honesty, privacy, and depth over superficiality. The 4\'s reliability gives the 7 stability, and the 7\'s insight adds wisdom to the 4\'s plans. Together you make careful, well-considered decisions. Quiet evenings together feel comfortable, not empty.'],
            ['Challenges', 'Both of you can be reserved and slow to express feelings, which may leave the relationship emotionally cool. The 4 may be too rigid for the 7\'s questioning mind, and the 7 may seem distant. Misunderstandings often hide in silence.'],
            ['How to Make It Work', 'Make deliberate space for emotional conversation and shared enjoyment. Show affection in practical ways, and speak your feelings aloud. With warmth added to respect, this pairing becomes steady and deeply trusting. Curiosity about each other\'s thoughts goes far.'],
        ]],
        '4-8' => ['title' => 'The Builder & the Achiever', 'sections' => [
            ['Overview', 'Life Path 4 and Life Path 8 are a powerful, productive pairing. Both are disciplined, practical, and focused on achievement, so this match tends to be goal-oriented, loyal, and strong. Together you can build something that lasts.'],
            ['Strengths Together', 'You respect each other\'s work ethic and share an interest in security and success. The 4\'s organization and the 8\'s vision combine well, and together you can build lasting financial and material stability. Both of you value loyalty and follow-through.'],
            ['Challenges', 'Work can dominate the relationship, leaving little time for emotion or play. The 8\'s desire for control may clash with the 4\'s stubbornness, and both of you may find it hard to show vulnerability. Stress can make you both stubborn.'],
            ['How to Make It Work', 'Schedule time for romance and rest, and keep decisions collaborative. Share praise and appreciation openly. When you balance ambition with affection, this partnership becomes a formidable and loving team. Remember that rest is productive, too.'],
        ]],
        '4-9' => ['title' => 'The Builder & the Humanitarian', 'sections' => [
            ['Overview', 'Life Path 4 and Life Path 9 pair practicality with idealism. The 4 is grounded and methodical, and the 9 is compassionate and big-picture, making a match that can be balancing or mismatched depending on respect. Opposites meet here, for better or worse.'],
            ['Strengths Together', 'The 4 offers the 9 structure and a way to turn ideals into action, and the 9 broadens the 4\'s perspective with compassion. Together you can accomplish meaningful work with a solid foundation. You learn patience and perspective from each other.'],
            ['Challenges', 'The 4 may see the 9 as impractical or unfocused, while the 9 may find the 4 too rigid or materialistic. Different priorities and emotional styles may cause misunderstandings. The 9 may feel limited, the 4 unsupported.'],
            ['How to Make It Work', 'Respect each other\'s strengths and find shared causes that need both planning and heart. Talk about values openly. When the 4\'s reliability supports the 9\'s vision, this partnership becomes grounded and meaningful. Curiosity about the other\'s world builds bridges.'],
        ]],
        '5-5' => ['title' => 'Two Adventurers', 'sections' => [
            ['Overview', 'Two Life Path 5s create a thrilling, spontaneous partnership. Both of you crave freedom, adventure, and new experiences, so this match tends to be exciting, social, and always in motion. Life together rarely feels ordinary.'],
            ['Strengths Together', 'You understand each other\'s need for independence and never try to cage each other. Travel, new interests, and shared curiosity keep the relationship fresh, and conversations rarely run dry. Spontaneity keeps both of you feeling young.'],
            ['Challenges', 'Neither of you may be eager to commit or settle, so stability can be a struggle. Restlessness, impulsiveness, and avoiding responsibilities can lead to inconsistency, financial chaos, or drifting apart. Both of you may dodge hard conversations.'],
            ['How to Make It Work', 'Agree on a few anchors, such as shared goals, honest check-ins, and basic routines. Make commitment feel like a choice, not a cage. When you combine adventure with loyalty, your bond becomes both thrilling and lasting. Plan something to look forward to. Honest check-ins keep freedom from becoming distance.'],
        ]],
        '5-6' => ['title' => 'The Adventurer & the Nurturer', 'sections' => [
            ['Overview', 'Life Path 5 and Life Path 6 combine freedom with devotion. The 5 loves change and exploration, and the 6 values home and commitment, forming a pairing that can feel like a push and pull between roaming and rooting. Both of you may learn what the other values most.'],
            ['Strengths Together', 'The 5 brings excitement and fresh perspectives, and the 6 offers warmth, stability, and care. When balanced, you help each other grow: the 5 learns to settle, and the 6 learns to loosen up.'],
            ['Challenges', 'The 6 may feel insecure or controlling when the 5 wants space, and the 5 may feel tied down by the 6\'s responsibilities and expectations. Different priorities around home and freedom can cause tension.'],
            ['How to Make It Work', 'Create a home that feels like a base for adventures, not a cage. The 6 can trust, and the 5 can reassure. With compromise and clear communication, you can enjoy both belonging and exploration. Humor softens tension.'],
        ]],
        '5-7' => ['title' => 'The Adventurer & the Seeker', 'sections' => [
            ['Overview', 'Life Path 5 and Life Path 7 are both curious, independent seekers. The 5 explores the world outwardly, and the 7 explores inwardly, so this match can be intellectual, unconventional, and full of discovery. Neither of you is likely to bore the other.'],
            ['Strengths Together', 'You appreciate each other\'s need for freedom and space. The 5\'s adventurous spirit stimulates the 7\'s curiosity, and the 7\'s depth gives the 5 new insight. Conversations can be lively, philosophical, and eye-opening. Curiosity is your shared engine.'],
            ['Challenges', 'The 5\'s restlessness and the 7\'s reserve can cause emotional distance. The 5 may feel the 7 is too withdrawn, and the 7 may find the 5 scattered. Both may avoid emotional vulnerability. Words may be few and misunderstandings common.'],
            ['How to Make It Work', 'Make time for both exploration and quiet, and share your feelings, not just your ideas. Be reliable about small things. When curiosity meets honesty, this pairing becomes a rich, freedom-respecting bond. Share small, real moments, not only big ideas.'],
        ]],
        '5-8' => ['title' => 'The Adventurer & the Achiever', 'sections' => [
            ['Overview', 'Life Path 5 and Life Path 8 combine adaptability with ambition. The 5 loves variety and freedom, and the 8 loves power and achievement, creating a dynamic pairing that is energetic, bold, and sometimes volatile. Neither of you is afraid of a challenge.'],
            ['Strengths Together', 'The 5\'s flexibility and charisma complement the 8\'s drive and organization. Together you can tackle big opportunities, take smart risks, and enjoy rewards. You share confidence and an appetite for living large. Your combined energy can be magnetic.'],
            ['Challenges', 'The 8\'s desire for control may clash with the 5\'s need for freedom, and the 5\'s unpredictability may frustrate the 8. Money, risk, and commitment can become areas of conflict. Both of you may push boundaries too far.'],
            ['How to Make It Work', 'Respect each other\'s different ways of working and set clear agreements about money and time. Give each other freedom and accountability. When you align your strengths, this partnership becomes a powerful engine. Take time to celebrate shared wins.'],
        ]],
        '5-9' => ['title' => 'The Adventurer & the Humanitarian', 'sections' => [
            ['Overview', 'Life Path 5 and Life Path 9 are both open-minded, adventurous, and curious about life. The 5 seeks experience, and the 9 seeks meaning, forming a worldly, generous pairing with wide horizons. Your shared curiosity creates a strong bond.'],
            ['Strengths Together', 'You share a love of travel, culture, and learning, and neither of you is narrow-minded. The 5\'s energy livens the 9\'s idealism, and the 9\'s compassion adds depth to the 5\'s adventures. Both of you value honesty and open minds.'],
            ['Challenges', 'Both of you may struggle with commitment or practical matters. The 5\'s restlessness can leave the 9 feeling unsettled, and the 9\'s emotional intensity or tendency to withdraw may confuse the 5. Neither may take responsibility for the practical side.'],
            ['How to Make It Work', 'Anchor your adventures with shared goals and honest conversations. Handle practical responsibilities together. When freedom and compassion are balanced, this pairing becomes rich, adventurous, and meaningful. Plan the logistics so the dreams can happen.'],
        ]],
        '6-6' => ['title' => 'Two Nurturers', 'sections' => [
            ['Overview', 'Two Life Path 6s create a loving, devoted partnership. Both of you value family, home, and caring for others, so this match tends to feel warm, loyal, and deeply nurturing. Home is the heart of this match.'],
            ['Strengths Together', 'You understand each other\'s need to give and protect. Together you create a beautiful, welcoming home and take care of friends and family generously. Loyalty and responsibility come easily to both of you. Both of you show love through thoughtful acts.'],
            ['Challenges', 'Both of you may take on too much, worry too much, or try to control what\'s best for the other. Neither may ask for help, and mutual perfectionism can lead to criticism or resentment. Resentment can build when giving goes unnoticed.'],
            ['How to Make It Work', 'Care for yourselves as well as each other, and let go of the need to fix everything. Share responsibilities and voice your needs. When love is balanced with boundaries, your partnership becomes a lasting, joyful haven. Let someone else care for you sometimes.'],
        ]],
        '6-7' => ['title' => 'The Nurturer & the Seeker', 'sections' => [
            ['Overview', 'Life Path 6 and Life Path 7 blend warmth with depth. The 6 focuses on caring connection, and the 7 on solitude and understanding, so this match can be tender but sometimes emotionally uneven. Patience and understanding are the keys here.'],
            ['Strengths Together', 'The 6\'s nurturing presence helps the 7 feel safe, and the 7\'s wisdom gives the 6 a different perspective. You can build a calm, respectful bond when you value each other\'s strengths. Loyalty runs deep when trust is earned.'],
            ['Challenges', 'The 6 may feel shut out by the 7\'s need for solitude, while the 7 may feel crowded by the 6\'s care and advice. Differences in emotional expression can leave both of you misunderstood. Offers of help can feel like pressure to the 7.'],
            ['How to Make It Work', 'Explain your needs openly, and create regular time for both closeness and space. When warmth meets honesty, this pairing becomes a deep, respectful bond. Reassurance without pressure helps the 7 return.'],
        ]],
        '6-8' => ['title' => 'The Nurturer & the Achiever', 'sections' => [
            ['Overview', 'Life Path 6 and Life Path 8 combine care with ambition. The 6 offers warmth and loyalty, and the 8 brings drive and success, forming a match that can be deeply supportive when each values the other\'s strengths.'],
            ['Strengths Together', 'The 8\'s ambition and security give the 6 confidence, while the 6\'s care softens the 8\'s edges. Together you can build a prosperous, loving life where both achievement and affection have a place.'],
            ['Challenges', 'The 8 may focus too much on work, leaving the 6 feeling neglected. The 6 may feel overpowered or silenced, and the 8 may dismiss the 6\'s feelings as too sensitive. Respect can erode if feelings are brushed aside.'],
            ['How to Make It Work', 'The 8 should make time for tenderness and listen without judging, and the 6 should speak up with confidence. Respect each other\'s different strengths. When care and ambition work together, this match becomes quietly formidable.'],
        ]],
        '6-9' => ['title' => 'The Nurturer & the Humanitarian', 'sections' => [
            ['Overview', 'Life Path 6 and Life Path 9 are both caring, compassionate souls. The 6 focuses on close family and home, and the 9 on the wider world, creating a warm, generous pairing with a shared wish to help others.'],
            ['Strengths Together', 'You share a love of helping others and creating harmony. The 6\'s loyalty grounds the 9\'s big-hearted ideals, and the 9\'s wisdom broadens the 6\'s perspective. Together you can build a relationship rooted in understanding and generosity.'],
            ['Challenges', 'The 9\'s attention to causes and the wider world may leave the 6 feeling secondary. The 6\'s need for closeness may feel limiting to the 9. Both of you may avoid conflict instead of resolving it.'],
            ['How to Make It Work', 'Make your relationship a priority within your bigger goals, and speak honestly about needs. Share volunteer work or creative projects. When closeness and compassion go hand in hand, this pairing becomes tender and meaningful. Honest talks keep small hurts from growing.'],
        ]],
        '7-7' => ['title' => 'Two Seekers', 'sections' => [
            ['Overview', 'Two Life Path 7s create a deep, intellectual, and introspective partnership. Both of you value truth, solitude, and understanding, so this match often feels calm, respectful, and quietly profound.'],
            ['Strengths Together', 'You understand each other\'s need for space and depth. Conversations can be endlessly fascinating, and you respect each other\'s independence. Together you can build a relationship based on trust and shared curiosity.'],
            ['Challenges', 'Both of you can be reserved and slow to express feelings, which may leave the relationship emotionally cool. Neither may readily volunteer feelings, and misunderstandings can hide in silence.'],
            ['How to Make It Work', 'Make deliberate space for emotional conversation and shared enjoyment. Show affection in practical ways, and speak your feelings aloud. With warmth added to respect, this pairing becomes steady and deeply trusting.'],
        ]],
        '7-8' => ['title' => 'The Seeker & the Achiever', 'sections' => [
            ['Overview', 'Life Path 7 and Life Path 8 combine depth with ambition. The 7 offers wisdom and insight, and the 8 brings drive and success, forming a match that can be powerful when each respects the other\'s strengths.'],
            ['Strengths Together', 'The 8\'s ambition and security give the 7 confidence, while the 7\'s wisdom helps the 8 make thoughtful decisions. Together you can build something both meaningful and lasting.'],
            ['Challenges', 'The 8 may focus too much on work and status, leaving the 7 feeling neglected. The 7 may feel overpowered or silenced, and the 8 may dismiss the 7\'s feelings as too sensitive. Respect can erode if feelings are brushed aside.'],
            ['How to Make It Work', 'The 8 should make time for tenderness and listen without judging, and the 7 should speak up with confidence. Respect each other\'s different strengths. When depth and ambition work together, this match becomes quietly formidable.'],
        ]],
        '7-9' => ['title' => 'The Seeker & the Humanitarian', 'sections' => [
            ['Overview', 'Life Path 7 and Life Path 9 are both thoughtful, spiritual, and compassionate. The 7 seeks truth through analysis, and the 9 through compassion, creating a deep, meaningful pairing with shared values.'],
            ['Strengths Together', 'You share a love of truth, learning, and helping others. The 7\'s analytical mind helps the 9\'s ideals become practical, and the 9\'s compassion softens the 7\'s reserve. Together you can build a relationship rooted in understanding and generosity.'],
            ['Challenges', 'The 9\'s attention to causes and the wider world may leave the 7 feeling secondary. The 7\'s need for solitude may feel like rejection to the 9. Both of you may avoid conflict instead of resolving it.'],
            ['How to Make It Work', 'Make your relationship a priority within your bigger goals, and speak honestly about needs. Share volunteer work or creative projects. When depth and compassion go hand in hand, this pairing becomes tender and meaningful.'],
        ]],
        '8-8' => ['title' => 'Two Achievers', 'sections' => [
            ['Overview', 'Two Life Path 8s create a powerful, ambitious partnership. Both of you value success, achievement, and material stability, so this match tends to be goal-focused, strong-willed, and full of shared drive.'],
            ['Strengths Together', 'Together you can accomplish a great deal. You understand each other\'s ambition and respect competence and results. Few obstacles can stand in your way when you align.'],
            ['Challenges', 'Power struggles are the main risk. Both of you like control, and neither enjoys giving way. Work can crowd out romance, and pride may keep you from admitting mistakes or showing vulnerability. Stress can make both of you blunt.'],
            ['How to Make It Work', 'Share leadership by playing to each other\'s strengths, and make space for rest and affection. Treat each other as partners, not rivals. When ambition is shared, you become a formidable team with real staying power.'],
        ]],
        '8-9' => ['title' => 'The Achiever & the Humanitarian', 'sections' => [
            ['Overview', 'Life Path 8 and Life Path 9 combine ambition with compassion. The 8 pursues material success, and the 9 pursues humanitarian ideals, creating a dynamic pairing that can be both powerful and purposeful.'],
            ['Strengths Together', 'The 8\'s drive and organization give the 9\'s ideals a platform, and the 9\'s compassion softens the 8\'s edges. Together you can build something both prosperous and meaningful.'],
            ['Challenges', 'The 8 may see the 9 as impractical or unfocused, while the 9 may find the 8 too materialistic or controlling. Different priorities and emotional styles may cause misunderstandings.'],
            ['How to Make It Work', 'Respect each other\'s strengths and find shared causes that need both planning and heart. Talk about values openly. When the 8\'s reliability supports the 9\'s vision, this partnership becomes grounded and meaningful.'],
        ]],
        '9-9' => ['title' => 'Two Humanitarians', 'sections' => [
            ['Overview', 'Two Life Path 9s create a compassionate, idealistic partnership. Both of you value generosity, compassion, and making a difference, so this match tends to feel warm, purposeful, and deeply meaningful.'],
            ['Strengths Together', 'You share a love of helping others and making the world better. Together you can inspire people and share a joyful, generous life. Your shared warmth draws people toward you.'],
            ['Challenges', 'Both of you may struggle with practical matters or avoid conflict. The 9\'s attention to causes and the wider world may leave the other feeling secondary. Both of you may avoid conflict instead of resolving it.'],
            ['How to Make It Work', 'Make your relationship a priority within your bigger goals, and speak honestly about needs. Share volunteer work or creative projects. When compassion and practicality go hand in hand, this pairing becomes inspiring and deeply fulfilling.'],
        ]],
    ],
    'masterNotes' => [
        '11' => 'Because one of you carries a master number 11, the relationship has an extra layer: an 11 moves between intuitive, high-voltage insight and the gentler, partnership-focused energy of its root 2.',
        '22' => 'Because one of you carries a master number 22, the relationship has an extra layer: a 22 moves between large-scale vision and the practical, steady energy of its root 4.',
        '33' => 'Because one of you carries a master number 33, the relationship has an extra layer: a 33 moves between selfless, healing devotion and the caring, home-centred energy of its root 6.',
    ],
];