<?php
declare(strict_types=1);

/* ════════════════════════════════════════════════════════════════════
   WRAP-JSON TOOL
   Converts every .json file in a source folder into a guarded .php
   file in a destination folder. The content is unchanged — it is just
   wrapped so the web server refuses to hand it out by URL (a plain
   .json file can be downloaded by anyone who guesses its address).

   Usage (run from the repository root):
     php tools/wrap-json.php <source-folder> <destination-folder>

   Example:
     php tools/wrap-json.php destiny-matrix/data/destiny-matrix-readings destiny-matrix/php/readings

   Re-run it any time the source JSON changes. Command line only.
   ════════════════════════════════════════════════════════════════════ */

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit('Forbidden');
}

// Needed so the round-trip check below can include the generated files.
define('SPIRITUAL_APP', true);

const END_MARKER = 'SPIRITUAL_JSON_END';

if ($argc !== 3) {
    fwrite(STDERR, "Usage: php tools/wrap-json.php <source-folder> <destination-folder>\n");
    exit(1);
}

$sourceDir = rtrim($argv[1], '/\\');
$destDir = rtrim($argv[2], '/\\');

if (!is_dir($sourceDir)) {
    fwrite(STDERR, "Source folder not found: {$sourceDir}\n");
    exit(1);
}
if (!is_dir($destDir) && !mkdir($destDir, 0755, true)) {
    fwrite(STDERR, "Could not create destination folder: {$destDir}\n");
    exit(1);
}

$files = glob($sourceDir . '/*.json') ?: [];
sort($files);

if (count($files) === 0) {
    fwrite(STDERR, "No .json files found in {$sourceDir}\n");
    exit(1);
}

$written = 0;
$skipped = 0;
$failed = 0;

foreach ($files as $file) {
    $name = basename($file, '.json');
    $raw = (string) file_get_contents($file);

    // Strip a UTF-8 byte-order mark if the file has one.
    if (strncmp($raw, "\xEF\xBB\xBF", 3) === 0) {
        $raw = substr($raw, 3);
    }
    $raw = rtrim($raw);

    if ($raw === '') {
        echo "SKIPPED  {$name}.json  (file is empty)\n";
        $skipped++;
        continue;
    }

    $decoded = json_decode($raw, true);
    if (json_last_error() !== JSON_ERROR_NONE) {
        echo "FAILED   {$name}.json  (invalid JSON: " . json_last_error_msg() . ")\n";
        $failed++;
        continue;
    }

    // The wrapper stores the JSON as raw text; make sure the text can
    // never contain the line that ends that block.
    if (preg_match('/^\s*' . END_MARKER . '/m', $raw)) {
        echo "FAILED   {$name}.json  (contains the reserved text " . END_MARKER . ")\n";
        $failed++;
        continue;
    }

    $php = "<?php\n"
        . "declare(strict_types=1);\n\n"
        . "// Generated by tools/wrap-json.php from {$name}.json — do not edit by hand.\n"
        . "// Edit the source JSON and run the tool again.\n\n"
        . "if (!defined('SPIRITUAL_APP')) {\n"
        . "    http_response_code(403);\n"
        . "    exit('Forbidden');\n"
        . "}\n\n"
        . "return json_decode(<<<'" . END_MARKER . "'\n"
        . $raw . "\n"
        . END_MARKER . ", true);\n";

    $target = $destDir . '/' . $name . '.php';
    if (file_put_contents($target, $php) === false) {
        echo "FAILED   {$name}.json  (could not write {$target})\n";
        $failed++;
        continue;
    }

    // Round-trip check: the generated file must give back exactly the
    // same data as the original JSON.
    $roundTrip = include $target;
    if ($roundTrip !== $decoded) {
        unlink($target);
        echo "FAILED   {$name}.json  (round-trip check did not match — file not written)\n";
        $failed++;
        continue;
    }

    echo "OK       {$name}.json -> {$target}\n";
    $written++;
}

echo "\nDone: {$written} written, {$skipped} skipped, {$failed} failed.\n";
exit($failed > 0 ? 1 : 0);